- name: Ensure EPEL repository is enabled
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: true
  when: ansible_distribution in ["Rocky", "CentOS", "RedHatEnterpriseLinux"]

- name: Ensure RPM Fusion free repository is enabled
  become: true
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm
    state: present
    update_cache: true
    disable_gpg_check: true
  when: ansible_distribution in ["Rocky", "CentOS", "RedHatEnterpriseLinux"]

- name: Ensure basic dnf packages are installed on system
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - bzip2
      - curl
      - bind-utils
      - dstat
      - etckeeper
      - ffmpeg
      - git
      - golang
      - golang-src
      - htop
      - iftop
      - info
      - iotop
      - iperf
      - iptables
      - iptraf-ng
      - mlocate
      - lshw
      - lsof
      - mtr
      - net-tools
      - nethogs
      - nload
      - nmap
      - openssh-clients
      - pandoc
      - python3
      - python3-devel
      - screen
      - sysstat
      - chrony
      - tcpdump
      - tmux
      - traceroute
      - tree
      - ufw
      - unzip
      - vim
      - wget
      - whois
      - xz
      - zip
      - ImageMagick
    state: present
    update_cache: true
    skip_broken: true
  when: ansible_distribution in ["Rocky", "CentOS", "RedHatEnterpriseLinux"]

- name: Set hostname to rockylinux95
  become: true
  ansible.builtin.hostname:
    name: rockylinux95

- name: Update all packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest  # noqa: package-latest
